import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { NavbarComponent } from '../components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  // 0xC99df554F832e635a597Bfe84CEfaf1804aAD729

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavbarComponent />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
